# Generated by Django 4.2.3 on 2023-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('equivalent_support', models.FloatField()),
                ('budgetary_application', models.CharField(max_length=200)),
                ('date_of_concession', models.DateTimeField(verbose_name='Date published')),
                ('subsidy', models.JSONField()),
                ('regulatory_bases_address', models.CharField(max_length=200)),
                ('support_type', models.JSONField()),
            ],
        ),
    ]
